# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signal.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csignal.proto\"\x1b\n\tSignalREQ\x12\x0e\n\x06signal\x18\x01 \x03(\x02\"\x1f\n\nPrediction\x12\x11\n\tpredicton\x18\x01 \x01(\t21\n\x06Signal\x12\'\n\nSendSignal\x12\n.SignalREQ\x1a\x0b.Prediction\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNALREQ']._serialized_start=16
  _globals['_SIGNALREQ']._serialized_end=43
  _globals['_PREDICTION']._serialized_start=45
  _globals['_PREDICTION']._serialized_end=76
  _globals['_SIGNAL']._serialized_start=78
  _globals['_SIGNAL']._serialized_end=127
# @@protoc_insertion_point(module_scope)
